---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sc-label-mutation
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./sc-label-mutation
  prune: true
  sourceRef:
    kind: GitRepository
    name: sc-fix
    namespace: tanzu-continuousdelivery-resources